name: CI - Test & Update README

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8

    - name: Run Linter
      run: flake8 . --max-line-length=120 --ignore=E402

    - name: Run Tests
      run: pytest -v || echo "No tests found, continuing..."

    - name: Update README (example)
      run: |
        # Just append timestamp to README for demo
        echo "Last CI run: $(date)" >> README.md

    - name: Configure Git for GitHub Actions
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Commit and push README changes
      run: |
        git add README.md
        git commit -m "docs: update build status [skip ci]" || echo "No changes to commit"
        git push origin main
